# Generated by Django 3.2.16 on 2023-07-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0002_alter_expresssaving_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal_wallet',
            name='saving_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
