# Generated by Django 3.2.16 on 2023-07-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0003_goal_wallet_saving_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='evaluation_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='goal',
            name='payment_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
