# Generated by Django 3.2.16 on 2023-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0004_auto_20230729_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='amount_to_save_per_notification',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
