# Generated by Django 3.2.16 on 2023-07-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0005_goal_amount_to_save_per_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
