# Generated by Django 3.2.16 on 2023-07-29 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0006_auto_20230729_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
