# Generated by Django 3.2.16 on 2023-07-31 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Goals', '0007_alter_deposit_deposit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('achieved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saving_type', models.CharField(choices=[('regular', 'Regular Saving'), ('fixed', 'Fixed Saving')], max_length=10)),
                ('reminder_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=10, null=True)),
                ('payment_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('achieved', 'Achieved')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupGoalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('group_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goals.groupgoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
