# Generated by Django 3.2.16 on 2023-07-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0008_groupgoal_groupgoalmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupgoal',
            name='goal_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupgoal',
            name='goal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
