# Generated by Django 3.2.16 on 2023-07-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0009_auto_20230731_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupgoal',
            old_name='target_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='groupgoal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
