# Generated by Django 3.2.16 on 2023-08-05 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0010_auto_20230731_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupgoal',
            name='shareable_link',
            field=models.CharField(blank=True, default='no', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupgoalmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
