# Generated by Django 3.2.16 on 2023-08-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0011_auto_20230805_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupgoal',
            name='shareable_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
