# Generated by Django 3.2.16 on 2023-08-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0012_alter_groupgoal_shareable_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupgoalmember',
            name='contribution_amount',
        ),
    ]
