# Generated by Django 3.2.16 on 2023-08-05 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Goals', '0013_remove_groupgoalmember_contribution_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGoalMember_contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_date', models.DateField(blank=True, null=True)),
                ('group_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goals.groupgoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
