# Generated by Django 3.2.16 on 2023-08-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0014_groupgoalmember_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='expresssaving',
            name='is_withdraw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
