# Generated by Django 3.2.16 on 2023-08-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0015_expresssaving_is_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='is_withdraw',
            field=models.CharField(blank=True, default='No', max_length=10, null=True),
        ),
    ]
