# Generated by Django 3.2.16 on 2023-08-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0016_deposit_is_withdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest_Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_deposit', models.DecimalField(decimal_places=2, default=0.06, max_digits=10)),
                ('fixed_deposit', models.DecimalField(decimal_places=2, default=0.08, max_digits=10)),
            ],
        ),
    ]
