# Generated by Django 3.2.16 on 2023-08-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0017_interest_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGoalActivites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goals.groupgoal')),
            ],
        ),
    ]
