# Generated by Django 3.2.16 on 2023-08-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0019_groupgoalactivites_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupgoalmember_contribution',
            name='is_withdraw',
            field=models.CharField(blank=True, default='No', max_length=10, null=True),
        ),
    ]
