# Generated by Django 3.2.16 on 2023-08-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0020_groupgoalmember_contribution_is_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupgoal',
            name='is_active',
            field=models.CharField(default='Yes', max_length=100),
        ),
    ]
