# Generated by Django 3.2.16 on 2023-09-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0021_groupgoal_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_active',
            field=models.CharField(default='Yes', max_length=100),
        ),
    ]
