# Generated by Django 3.2.16 on 2023-09-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0022_goal_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='tax_Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate_value', models.DecimalField(decimal_places=2, default=0.2, max_digits=10)),
            ],
        ),
    ]
