# Generated by Django 3.2.16 on 2023-09-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0023_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='notification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
